### ISSUE TITLE
Problem in model construction - NOT an ISSUE (user query)

### ISSUE THREAD

**Issue by ayamgupta** [HAN-Siyu/LncFinder#1]
Hi, 

I have been trying to train a model for custom analysis but for some reason i am getting the following error. can anyone can help me with this regard?\
Error in checkForRemoteErrors(val) : 
  8 nodes produced errors; first error: Need numeric dependent variable for regression.

**Comment by HAN-Siyu** [comment]
> Hi,
> 
> I have been trying to train a model for custom analysis but for some reason i am getting the following error. can anyone can help me with this regard?
> Error in checkForRemoteErrors(val) :
> 8 nodes produced errors; first error: Need numeric dependent variable for regression.

Hi! Thank you very much for using LncFinder. Could you please share more information regarding the error? For example, which function you were running when the error threw. And what the input looks like? Thanks!

**Comment by papelypluma** [comment]
Hi @HAN-Siyu. I also got this error when I ran the build_model function. For reference, this is command I used:

>  fly.model <- build_model(fly.ncrna, fly.mrna, fly.frequencies, SS.features=FALSE, lncRNA.format="DNA", mRNA.format="DNA", folds.num=10, seed=1, gamma.range=(2^seq(-5, 0, 1)), cost.range=c(1, 4, 8, 16, 24, 32))

Any help is much appreciated. Thank you.

**Comment by papelypluma** [comment]
Just to add detail. The error comes out during SVM.tune processing.

**Comment by HAN-Siyu** [comment]
> Just to add detail. The error comes out during SVM.tune processing.

Hi! Thanks for using LncFinder! 

If you don't mind, could you please share your fly.ncrna, fly.mrna and fly.frequencies files, so that I can better locate the problem. If the files are not too big, you can send them via: siyu.han@helmholtz-muenchen.de.

**Comment by HAN-Siyu** [comment]
> Just to add detail. The error comes out during SVM.tune processing.

Hi papelypluma, I already located the problem. Seems that this issue comes from the update of LncFinder's dependencies.
I will update LncFinder accordingly now. Will let you know when the new version is available.

**Comment by HAN-Siyu** [comment]
> Just to add detail. The error comes out during SVM.tune processing.

@papelypluma @ayamgupta 
Hi! I already located the problem. Seems that this issue comes from the update of LncFinder's dependencies.
I will update LncFinder accordingly now. Will let you know when the new version is available.

**Comment by HAN-Siyu** [comment]
@papelypluma @ayamgupta 

Hi! I just updated LncFinder. It may take a few days for the new version to be available on CRAN. Before that, please download and install v1.15 here manually: https://github.com/HAN-Siyu/LncFinder/blob/master/R%20Package/LncFinder_1.1.5.tar.gz

Please check if the current version still throws the error when building new models. Thank you very much for pointing this issue out and helping improve LncFinder.

Siyu

**Comment by papelypluma** [comment]
Hi @HAN-Siyu Siyu. Thank you so much for looking into this issue! I tried the entire workflow with build_model to generate a customized training object, and the entire process worked without errors. Looks like the issue has been addressed with this version of LncFinder (v.1.1.5).
