### ISSUE TITLE
build model

### ISSUE THREAD

**Issue by Lordhooze** [HAN-Siyu/LncFinder#2]
Dear han:
I want to identify LncRNA in goose. So I need to build a model.
Can you tell me how many genes should I use to build model?
lncRNA ?
mRNA ? 

thank you very much
jiaxiang hu

**Comment by HAN-Siyu** [comment]
> Dear han: I want to identify LncRNA in goose. So I need to build a model. Can you tell me how many genes should I use to build model? lncRNA ? mRNA ?
> 
> thank you very much jiaxiang hu

Hi @Lordhooze , thanks for using LncFinder. Generally the more genes/transcripts used to train the model, the better the performance of the model. It's hard to say how many sequences are sufficient without any evaluations. Probably start from a few thousand sequences for mRNA and lncRNA?
